const subjects = {
  AlgoritmiIProgramiranje: { id: 0, name: 'Algoritmi i programiranje', },
  DigitalnaElektronika: { id: 0, name: 'Digitalna Elektronika', },
  UvodURačunarstvo: { id: 0, name: 'Uvod u računarstvo', },
  Matematika1: { id: 0, name: 'Matematika 1', },
  Matematika2: { id: 0, name: 'Matematika 2', },
  Matematika3: { id: 0, name: 'Matematika 3', },
  DiskretnaMatematika: { id: 0, name: 'Diskretna matematika', },
  TeorijaGrafova: { id: 0, name: 'Teorija Grafova', },
  VerovatnoćaIStatistika: { id: 0, name: 'Verovatnoća i statistika', },
  Fizika: { id: 0, name: 'Fizika', },
  ElektronskeKomponente: { id: 0, name: 'Elektronske komponente', },
  ObjektnoOrijentisanoProgramiranje: { id: 0, name: 'Objektno orijentisano programiranje ( C++)', },
  ProgramskiJezici: { id: 0, name: 'Programski jezici ( Java, C#)', },
  StrukturePodataka: { id: 0, name: 'Strukture podataka ( C++)', },
  RacunarskiSistemi: { id: 0, name: 'Računarski sistemi', },
  OrganizacijaRačunarskogSistema: { id: 0, name: 'Organizacija računarskog sistema', },
  ArhitekturaIOrganizacijaRačunara1: { id: 0, name: 'Arhitektura i organizacija računara 1', },
  BazePodataka: { id: 0, name: 'Baze podataka', },
  MikroprocesorskiSistemi: { id: 0, name: 'Mikroprocesorski sistemi', },
  Programiranje1Python: { id: 0, name: 'Programiranje 1 (Python)', },
  Programiranje2C: { id: 0, name: 'Programiranje 2 (C)', },
  OrganizacijaRačunarskeTehnike: { id: 0, name: 'Organizacija računarske tehnike', },
  WebProgramiranje: { id: 0, name: 'Web programiranje', },
  RacunarskaGrafika: { id: 0, name: 'Računarska grafika', },
  VestackaInteligencija: { id: 0, name: 'Veštačka inteligencija', },
  OsnoviElektronike: { id: 0, name: 'Osnovi elektronike', },
  ImpulsnaIDigitalnaElektronskaKola: { id: 0, name: 'Impulsna i digitalna elektronska kola', },
  ArhitektureDigitalnihSistema: { id: 0, name: 'Arhitekture digitalnih sistema', },
  NumeričkaMatematika: { id: 0, name: 'Numerička matematika', },
  ParalelniSistemi: { id: 0, name: 'Paralelni sistemi', },
};

const tutors = [
  // {
  //   id: 11,
  //   link: '',
  //   name: 'Jasmina',
  //   description: 'Časovi iz Paralelnih sistema, zadaci i teorija!',
  //   subjects: [subjects.ParalelniSistemi],
  //   price: {
  //     personally: 1000,
  //     group: null,
  //   },
  //   rating: [],
  // },
  {
    id: 10,
    link: 'https://www.instagram.com/direct/t/116366959757524/',
    name: 'Mina',
    description:
      'Diplomirani matematičar sa 10 godina iskustva u nastavi drži časove matematike, individualno ili u malim grupama - do 4 studenta. Sa fokusom na vaše potrebe i ciljeve, uz individualan pristup i prilagodjen tempo, naš zajednički rad će biti usmeren ka tome da ispit pripremite sa lakoćom.',
    subjects: [
      subjects.Matematika1,
      subjects.Matematika2,
      subjects.Matematika3,
      subjects.DiskretnaMatematika,
      subjects.TeorijaGrafova,
      subjects.VerovatnoćaIStatistika,
    ],
    price: {
      personally: 2000,
      group: 1000,
    },
    rating: [],
  },
  {
    id: 9,
    link: 'https://www.instagram.com/direct/t/111252743606139/',
    name: 'Andrija',
    description:
      'Kompletna priprema. I teorija i zadaci. Sve ono što novi profesor traži. Polaganje zagarantovano!',
    subjects: [subjects.DiskretnaMatematika],
    price: {
      personally: 800,
      group: 600,
    },
    rating: [],
  },
  {
    id: 8,
    link: 'https://www.instagram.com/direct/t/108508627206967/',
    name: 'Petar',
    description:
      'Iskustvo s predavanjem predmeta vezanih za analognu i digitalnu elektroniku, C i VHDL',
    subjects: [
      subjects.OsnoviElektronike,
      subjects.DigitalnaElektronika,
      subjects.ObjektnoOrijentisanoProgramiranje,
      subjects.ImpulsnaIDigitalnaElektronskaKola,
      subjects.ArhitektureDigitalnihSistema,
      subjects.NumeričkaMatematika,
      subjects.Matematika3,
    ],
    price: {
      personally: 700,
      group: 500,
    },
    rating: [],
  },
  {
    id: 7,
    link: 'https://www.instagram.com/direct/t/112004303531637/',
    name: 'Andrija',
    description:
      'Priprema kolokvijuma i ispita, pomoc pri izradi laboratorijskih vežbi. Fleksibilno vreme i prilagođavanje vašim potrebama. Mogućnost online predavanja.',
    subjects: [
      subjects.UvodURačunarstvo,
      subjects.AlgoritmiIProgramiranje,
      subjects.ObjektnoOrijentisanoProgramiranje,
      subjects.ProgramskiJezici,
      subjects.StrukturePodataka,
      subjects.WebProgramiranje,
      subjects.RacunarskaGrafika,
      subjects.VestackaInteligencija,
    ],
    price: {
      personally: 1000,
      group: 500,
    },
    rating: [],
  },
  {
    id: 6,
    link: 'https://www.instagram.com/direct/t/113975953328518/',
    name: 'Filip',
    description: '',
    subjects: [
      subjects.AlgoritmiIProgramiranje,
      subjects.DigitalnaElektronika,
      subjects.UvodURačunarstvo,
    ],
    price: {
      personally: 400,
      group: 300,
    },
    rating: [],
  },
  {
    id: 5,
    link: 'https://www.instagram.com/direct/t/17844869285287110/',
    name: 'Jelena',
    description: '',
    subjects: [
      subjects.Matematika1,
      subjects.Matematika2,
      subjects.Matematika3,
      subjects.DiskretnaMatematika,
      subjects.TeorijaGrafova,
      subjects.VerovatnoćaIStatistika,
    ],
    price: {
      personally: null,
      group: 800,
    },
    rating: [],
  },
  {
    id: 4,
    link: 'https://www.facebook.com/messages/e2ee/t/7521900767862414',
    name: 'Jovana',
    description:
      'Višegodišnje iskustvo u držanju privatne nastave i iskustvo predavača u srednjoj školi.',
    subjects: [subjects.AlgoritmiIProgramiranje],
    price: {
      personally: 1500,
      group: 1200,
    },
    rating: [],
  },
  {
    id: 2,
    link: 'link',
    name: 'Aleksandra',
    description: '',
    subjects: [
      subjects.AlgoritmiIProgramiranje,
      subjects.UvodURačunarstvo,
      subjects.ElektronskeKomponente,
      subjects.ObjektnoOrijentisanoProgramiranje,
      subjects.ProgramskiJezici,
      subjects.StrukturePodataka,
      subjects.RacunarskiSistemi,
      subjects.OrganizacijaRačunarskogSistema,
      subjects.ArhitekturaIOrganizacijaRačunara1,
      subjects.DiskretnaMatematika,
      subjects.BazePodataka,
      subjects.MikroprocesorskiSistemi,
      subjects.Programiranje1Python,
      subjects.Programiranje2C,
      subjects.OrganizacijaRačunarskeTehnike,
    ],
    price: {
      personally: 1000,
      group: 1000,
    },
    rating: [
      {
        link: '',
        name: '',
        rate: 1,
        comment: '',
        subject: subjects.AlgoritmiIProgramiranje,
        time: new Date(),
      },
    ],
  },
  {
    id: 1,
    link: 'link',
    name: 'Aleksandra',
    description:
      'Višegodišnje iskustvo u pripremi studenata za uspešno polaganje ispita iz fizike na Elektronskom fakultetu.',
    subjects: [subjects.Fizika],
    price: {
      personally: 1500,
      group: 1000,
    },
    rating: [],
  },
];

export default tutors;
