import Nignite from '../../assets/companies/Nignite.jpg';
import AccordiaGroup from '../../assets/companies/AccordiaGroup.png';
import Codemancy from '../../assets/companies/Codemancy.jpg';
import Deavensoft from '../../assets/companies/Deavensoft.jpg';
import InfinitoMedia from '../../assets/companies/InfinitoMedia.jpg';
import Ingsoftware from '../../assets/companies/Ingsoftware.jpg';
import ITLabs from '../../assets/companies/ITLabs.png';
import JoomBooz from '../../assets/companies/JoomBooz.jpg';
import Softelm from '../../assets/companies/Softelm.jpg';
import SyncitGroup from '../../assets/companies/SyncitGroup.png';
import WebNi from '../../assets/companies/WebNi.jpg';
import DualSoft from '../../assets/companies/DualSoft.jpg';
import Diligent from '../../assets/companies/Diligent.jpg';

const companies = [
  {
    name: 'Diligent',
    logo: Diligent,
    tags: ['.NET', 'NodeJS', 'ReactJS', 'Angular', 'ReactNative', 'Next.js'],
    link: 'https://itfirmeunisu.rs/diligent/website',
    linkName: 'dilig.net',
    internship: 'https://www.instagram.com/p/C379sKDMYaQ/?img_index=1',
  },
  {
    name: 'Dual Soft',
    logo: DualSoft,
    tags: [
      'JavaScript',
      'Angular',
      'Java',
      'Oracle',
      'Redis',
      'Ionic',
      'Kafka',
      'Docker',
      'Cassandra',
      'Kubernetes',
      'HTML',
      'RabbitMQ',
      'CSS',
    ],
    link: 'https://itfirmeunisu.rs/dual-soft/website',
    linkName: 'dualsoft.rs',
    internship: 'https://www.instagram.com/p/C32Tf8ps9w1/?img_index=1',
  },
  {
    name: 'WebNi',
    logo: WebNi,
    tags: ['WordPress'],
    link: 'https://itfirmeunisu.rs/webni/website',
    linkName: 'webni.me',
    internship: '',
  },
  {
    name: 'Syncit Group',
    logo: SyncitGroup,
    tags: [
      'Computer Vision',
      'NLP',
      'Transformers',
      'PyTorch',
      'TensorFlow',
      'Scikit Learn',
      'Pandas',
      'Python',
      'Laravel',
      'WordPress',
      'Magento',
      'Vue.js',
      'Android',
      'JavaScript',
      'PHP',
      'ReactJS',
      'Angular',
      'iOS',
      'jQuery',
      'Docker',
      'Drupal',
      'CakePHP',
      'WooCommerce',
    ],
    link: 'https://itfirmeunisu.rs/syncit-group/website',
    linkName: 'syncitgroup.com',
    internship: '',
  },
  {
    name: 'Softelm',
    logo: Softelm,
    tags: ['Laravel', 'ReactJS', 'Angular', 'ReactNative', 'Ionic'],
    link: 'https://softelm.com/?ref=itfirmeunisu.rs',
    linkName: 'softelm.com',
    internship: '',
  },
  {
    name: 'Joombooz',
    logo: JoomBooz,
    tags: [
      'CMS WordPress ',
      'Digitalni Marketing',
      'JavaScript',
      'PHP',
      'MySQL',
      'jQuery',
    ],
    link: 'https://www.joombooz.com/?ref=itfirmeunisu.rs',
    linkName: 'joombooz.com',
    internship: '',
  },
  {
    name: 'ITLabs',
    logo: ITLabs,
    tags: [
      'C#',
      'Java',
      'JavaScript',
      'Angular',
      'React',
      'nodeJS',
      'Python',
      'PHP',
      'Vue.js',
      'AWS',
      'Google Cloud',
      'Microsoft Azure',
      'Ruby',
    ],
    link: 'https://www.it-labs.com/',
    linkName: 'it-labs.com',
    internship: '',
  },
  {
    name: 'Ingsoftware',
    logo: Ingsoftware,
    tags: [
      '.NET',
      'Java',
      'nopCommerce',
      'NodeJS',
      'Angular',
      'Vue.js',
      'React',
      'NextJS',
      'Svelte(Kit)',
      'Swift',
      'Kotlin',
      'Flutter',
      'React Native',
      '.NET MAUI',
      'PostgreSQL',
      'SQL Server',
      'MySQL',
      'MongoDB',
      'Redis',
      'TimescaleDB',
      'Apache Kafka',
      'Elasticsearch',
      'Docker',
      'AWS',
      'Azure',
      'Google Cloud',
      'Firebase',
      'Netlify',
      'Vercel',
    ],
    link: 'https://itfirmeunisu.rs/ingsoftware/website',
    linkName: 'ingsoftware.com',
    internship: '',
  },

  {
    name: 'InfinitoMedia',
    logo: InfinitoMedia,
    tags: [
      'CMS WordPress',
      'PHP',
      'HTML',
      'CSS',
      'JavaScript',
      'Grafičkim dizajn',
      'Google Ads',
      'Social Media Marketing',
    ],
    link: 'https://itfirmeunisu.rs/infinito-media',
    linkName: 'infinitomedia.rs',
    internship: '',
  },
  {
    name: 'Deavensoft',
    logo: Deavensoft,
    tags: ['Java', 'Spring', 'Vue.js', 'Elasticsearch', 'Docker', 'AWS'],
    link: 'https://itfirmeunisu.rs/deavensoft/website',
    linkName: 'deavensoft.com',
    internship: '',
  },
  {
    name: 'Codemancy',
    logo: Codemancy,
    tags: [
      'C#',
      'JavaScript',
      'NodeJS',
      'Angular',
      'MySQL',
      'ASP.NET',
      'jQuery',
      'TypeScript',
      '.NET core',
      'MongoDB',
      'Razor',
      'Liquid templates',
    ],
    link: 'https://codemancystudio.com/?ref=itfirmeunisu.rs',
    linkName: 'codemancystudio.com',
    internship: '',
  },
  {
    name: 'Accordia Group',
    logo: AccordiaGroup,
    tags: [
      'MS SQL Server',
      ' WCF',
      ' WPF',
      'C#',
      'Java',
      'Sybase',
      'Spring',
      'SpringBoot',
      'JUnit',
      'TestNG',
      'Maven',
      'Gradle',
      '.NET',
      'Entity Framework',
      'Angular',
      'Node.js',
      'nginx',
      'Docker',
      'Kubernetes',
      'Azure',
      'Azure DevOps',
      'Cloudflare',
      'React',
      'Ractnative',
    ],
    link: 'https://itfirmeunisu.rs/accordia-group/website',
    linkName: 'accordia-group.com',
    internship: '',
  },
  {
    name: 'Nignite',
    logo: Nignite,
    tags: ['C#', 'JavaScript', 'Angular'],
    link: 'https://www.nignite.com',
    linkName: 'nignite.com',
    internship: '',
  },
];

export default companies;
