name: 🚀 Deploy backend on main push

on:
  push:
    branches:
      - main
    paths:
      - "backend/**/*"

jobs:
  build_and_deploy:
    name: 🚀 Deploy backend on main push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_SERVER_IP }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            cd ${{ secrets.CONTABO_BACKEND_PROD }} 
            git pull
            pm2 restart backendProduction
