name: 🚀 Deploy frontend on main push

on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**/*"

jobs:
  web-deploy:
    name: 🚀 Deploy frontend on main push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_SERVER_IP }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            cd ${{ secrets.CONTABO_FRONTEND_PROD }} 
            git pull
            npm run build
